#!/usr/bin/env python3
import feedparser
import re
import subprocess

def parse_episode(str):
    m = re.search('(.*)[ .][sS](\d{1,2})[eE](\d{1,2})', str)
    show = m.group(1)
    season = int(m.group(2))
    episode = int(m.group(3))
    id = f'{show} S{season:02}E{episode:02}'

feed = feedparser.parse('http://showrss.info/user/236333.rss?magnets=true&namespaces=true&name=null&quality=fhd&re=yes')
links = [item['link'] for item in feed['items']]

subprocess.run(['aria2c', '--seed-time=0', '--max-concurrent-downloads=40'] + links, cwd='/home/patrick/.download')
